cmake_minimum_required(VERSION 3.16)
project(garfield_field LANGUAGES CXX)
find_package(ROOT REQUIRED COMPONENTS Core Graf Gpad Gui)
find_package(Garfield REQUIRED)
add_executable(garfield-field main.cc)
target_compile_features(garfield-field PRIVATE cxx_std_17)
target_link_libraries(garfield-field PRIVATE Garfield::Garfield ROOT::Core ROOT::Graf ROOT::Gpad ROOT::Gui)
enable_testing()
add_test(NAME uniform-field COMMAND garfield-field --batch)
